services:
  app:
    build:
      dockerfile: .docker/Dockerfile
      context: .
      target: dev
    volumes:
      - .:/app
    networks:
      - default
    environment:
      - SPRING_DATA_MONGODB_HOST=mongodb
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-app:3306/database
    depends_on:
      - mysql-keycloack
      - mysql-app
      - mongodb
    ports:
      - "8080:8080"

  mysql-keycloack:
    image: mysql:8.0
    networks:
      - default
    ports:
      - "3307:3306"
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - .docker/mysql-keycloack-data:/var/lib/mysql
      - .docker/keycloack-init.sql:/docker-entrypoint-initdb.d/keycloack-init.sql

  mysql-app:
    image: mysql:8.0
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      - MYSQL_USER=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - .docker/mysql-app-data:/var/lib/mysql

  keycloack:
    image: quay.io/keycloak/keycloak:26.1.4
    networks:
      - default
    ports:
      - "8000:8080"
    depends_on:
      - mysql-keycloack
    entrypoint: "/opt/keycloak/bin/kc.sh start-dev"
    environment:
      - KC_BOOTSTRAP_ADMIN_PASSWORD=password
      - KC_BOOTSTRAP_ADMIN_USERNAME=username
      - KC_DB=mysql
      - KC_DB_USERNAME=username
      - KC_DB_PASSWORD=password
      - KC_DB_URL=jdbc:mysql://mysql-keycloack:3306/database

  mongodb:
    image: mongo:7.0
    networks:
      - default
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=username
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=database
    volumes:
      - .docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - .docker/mongo-app-data:/data/db


networks:
  default: